"""add router identity and version fields

Revision ID: 16ec79fb3c8d
Revises: 51975ae09644
Create Date: 2026-02-08 22:45:03.962588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ec79fb3c8d'
down_revision: Union[str, None] = '51975ae09644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('identity', sa.String(length=255), nullable=True))
    op.add_column('routers', sa.Column('routeros_version', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routers', 'routeros_version')
    op.drop_column('routers', 'identity')
    # ### end Alembic commands ###
