"""make cidr_disponibles required in routers

Revision ID: 414cce708fed
Revises: 87458cb9eb78
Create Date: 2026-02-08 23:22:18.339645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414cce708fed'
down_revision: Union[str, None] = '87458cb9eb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routers', 'cidr_disponibles',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routers', 'cidr_disponibles',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
