"""add router uptime monitoring fields

Revision ID: 661c8de35753
Revises: 527a0e141b2d
Create Date: 2026-02-08 22:17:25.172865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661c8de35753'
down_revision: Union[str, None] = '527a0e141b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('routers', sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('routers', sa.Column('last_online_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routers', 'last_online_at')
    op.drop_column('routers', 'last_check_at')
    op.drop_column('routers', 'is_online')
    # ### end Alembic commands ###
