"""add role_permissions table

Revision ID: 756faf8fb918
Revises: b2c3d4e5f6a7
Create Date: 2026-02-05 14:17:52.400825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '756faf8fb918'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('rol', postgresql.ENUM('ADMIN', 'OPERADOR', 'TECNICO', 'AUDITOR', 'SOPORTE', name='rolusuario', create_type=False), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol', 'module', name='uq_rol_module')
    )
    op.create_index(op.f('ix_role_permissions_module'), 'role_permissions', ['module'], unique=False)
    op.create_index(op.f('ix_role_permissions_rol'), 'role_permissions', ['rol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permissions_rol'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_module'), table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
