"""add routers and mikrotik fields to contratos

Revision ID: 7df6ecd40cd2
Revises: cfb62b8ae220
Create Date: 2026-02-05 18:13:08.749186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df6ecd40cd2'
down_revision: Union[str, None] = 'cfb62b8ae220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
