"""add router events table

Revision ID: 87458cb9eb78
Revises: 16ec79fb3c8d
Create Date: 2026-02-08 22:54:46.095910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87458cb9eb78'
down_revision: Union[str, None] = '16ec79fb3c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('router_events',
    sa.Column('router_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_router_events_event_type'), 'router_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_router_events_router_id'), 'router_events', ['router_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_router_events_router_id'), table_name='router_events')
    op.drop_index(op.f('ix_router_events_event_type'), table_name='router_events')
    op.drop_table('router_events')
    # ### end Alembic commands ###
