"""add routers and mikrotik fields to contratos

Revision ID: cfb62b8ae220
Revises: 4114a08f3d6b
Create Date: 2026-02-05 15:50:06.136548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb62b8ae220'
down_revision: Union[str, None] = '4114a08f3d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routers',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('puerto', sa.Integer(), nullable=False),
    sa.Column('ssl', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routers_ip'), 'routers', ['ip'], unique=False)
    op.add_column('contratos', sa.Column('ip_asignada', sa.String(length=50), nullable=True))
    op.add_column('contratos', sa.Column('router_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contratos', 'routers', ['router_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contratos', type_='foreignkey')
    op.drop_column('contratos', 'router_id')
    op.drop_column('contratos', 'ip_asignada')
    op.drop_index(op.f('ix_routers_ip'), table_name='routers')
    op.drop_table('routers')
    # ### end Alembic commands ###
