"""add_motivo_cancelacion_to_instalaciones

Revision ID: df7f9d9bc198
Revises: 6e7864c6747c
Create Date: 2026-02-06 03:28:57.124189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df7f9d9bc198'
down_revision: Union[str, None] = '6e7864c6747c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instalaciones', sa.Column('motivo_cancelacion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instalaciones', 'motivo_cancelacion')
    # ### end Alembic commands ###
