"""add_cidr_disponibles_to_routers

Revision ID: df9ad1f457f3
Revises: f03ace1a35f6
Create Date: 2026-02-06 03:49:22.177761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9ad1f457f3'
down_revision: Union[str, None] = 'f03ace1a35f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('cidr_disponibles', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routers', 'cidr_disponibles')
    # ### end Alembic commands ###
