"""add instalaciones module with temp client data


Revision ID: e333da831bec
Revises: 68b14cdd71bd
Create Date: 2026-02-04 23:11:37.261195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e333da831bec'
down_revision: Union[str, None] = '68b14cdd71bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'solicitud' to EstadoInstalacion enum (at the beginning)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_enum
                WHERE enumlabel = 'solicitud'
                AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'estadoinstalacion')
            ) THEN
                -- First, let's check which values exist and add solicitud appropriately
                -- We'll add it at the end for now to avoid ordering issues
                ALTER TYPE estadoinstalacion ADD VALUE 'solicitud';
            END IF;
        END $$;
    """)

    op.add_column('contratos', sa.Column('pdf_firmado_path', sa.String(length=500), nullable=True))
    op.add_column('instalaciones', sa.Column('numero_instalacion', sa.String(length=20), nullable=False))
    op.add_column('instalaciones', sa.Column('plan_id', sa.UUID(), nullable=False))
    op.add_column('instalaciones', sa.Column('temp_tipo_identificacion', sa.String(length=20), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_numero_identificacion', sa.String(length=20), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_nombre', sa.String(length=100), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_apellido1', sa.String(length=100), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_apellido2', sa.String(length=100), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_razon_social', sa.String(length=255), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_email', sa.String(length=255), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_telefono', sa.String(length=20), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_provincia', sa.String(length=50), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_canton', sa.String(length=50), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_distrito', sa.String(length=50), nullable=True))
    op.add_column('instalaciones', sa.Column('temp_direccion_exacta', sa.Text(), nullable=True))
    op.add_column('instalaciones', sa.Column('pdf_solicitud_path', sa.String(length=500), nullable=True))
    op.alter_column('instalaciones', 'contrato_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_instalaciones_numero_instalacion'), 'instalaciones', ['numero_instalacion'], unique=True)
    op.create_foreign_key(None, 'instalaciones', 'planes', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instalaciones', type_='foreignkey')
    op.drop_index(op.f('ix_instalaciones_numero_instalacion'), table_name='instalaciones')
    op.alter_column('instalaciones', 'contrato_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('instalaciones', 'pdf_solicitud_path')
    op.drop_column('instalaciones', 'temp_direccion_exacta')
    op.drop_column('instalaciones', 'temp_distrito')
    op.drop_column('instalaciones', 'temp_canton')
    op.drop_column('instalaciones', 'temp_provincia')
    op.drop_column('instalaciones', 'temp_telefono')
    op.drop_column('instalaciones', 'temp_email')
    op.drop_column('instalaciones', 'temp_razon_social')
    op.drop_column('instalaciones', 'temp_apellido2')
    op.drop_column('instalaciones', 'temp_apellido1')
    op.drop_column('instalaciones', 'temp_nombre')
    op.drop_column('instalaciones', 'temp_numero_identificacion')
    op.drop_column('instalaciones', 'temp_tipo_identificacion')
    op.drop_column('instalaciones', 'plan_id')
    op.drop_column('instalaciones', 'numero_instalacion')
    op.drop_column('contratos', 'pdf_firmado_path')
    # ### end Alembic commands ###
