"""initial schema

Revision ID: e57874f192a1
Revises: 
Create Date: 2026-02-04 19:13:32.505307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57874f192a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('tipo_identificacion', sa.Enum('CEDULA_FISICA', 'CEDULA_JURIDICA', 'DIMEX', 'NITE', name='tipoidentificacion'), nullable=False),
    sa.Column('numero_identificacion', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido1', sa.String(length=100), nullable=True),
    sa.Column('apellido2', sa.String(length=100), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.Column('canton', sa.String(length=50), nullable=True),
    sa.Column('distrito', sa.String(length=50), nullable=True),
    sa.Column('direccion_exacta', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_numero_identificacion'), 'clientes', ['numero_identificacion'], unique=True)
    op.create_table('planes',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('velocidad_bajada_mbps', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('velocidad_subida_mbps', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'OPERADOR', 'LECTURA', name='rolusuario'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('contratos',
    sa.Column('numero_contrato', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'SUSPENDIDO', 'CANCELADO', 'PENDIENTE', name='estadocontrato'), nullable=False),
    sa.Column('dia_facturacion', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_numero_contrato'), 'contratos', ['numero_contrato'], unique=True)
    op.create_table('facturas',
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('clave_numerica_fe', sa.String(length=50), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impuesto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'EMITIDA', 'ANULADA', name='estadofactura'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_numero_factura'), 'facturas', ['numero_factura'], unique=True)
    op.create_table('instalaciones',
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('fecha_programada', sa.Date(), nullable=False),
    sa.Column('fecha_completada', sa.Date(), nullable=True),
    sa.Column('tecnico_asignado', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA', name='estadoinstalacion'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'SINPE_MOVIL', 'TARJETA', 'DEPOSITO', name='metodopago'), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('periodo_facturado', sa.String(length=7), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'VALIDADO', 'RECHAZADO', name='estadopago'), nullable=False),
    sa.Column('validado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['validado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('instalaciones')
    op.drop_index(op.f('ix_facturas_numero_factura'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_contratos_numero_contrato'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('planes')
    op.drop_index(op.f('ix_clientes_numero_identificacion'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
