"""add_motivo_cancelacion_to_instalaciones

Revision ID: f03ace1a35f6
Revises: df7f9d9bc198
Create Date: 2026-02-06 03:34:05.782199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03ace1a35f6'
down_revision: Union[str, None] = 'df7f9d9bc198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
